### ISSUE TITLE
missing styles in example for current Chrome release

### ISSUE THREAD

**Issue by DanielRuf** [react-dnd/react-dnd#550]
https://gaearon.github.io/react-dnd/docs-tutorial.html

In the current Chrome version (52) on MacOS the board is not shown because we have to apply some more styles to the outer elements, something like

``` css
html, body, #root {
    width: 100%;
    height:100%;
    display:inline-block;
}
```

Also this makes problems:

``` html
return connectDropTarget(
    <div style={{ position: 'relative', display: 'inline-block', width: '100%', height: '100%' }}>
```

But this works:

``` html
return connectDropTarget(
      <div style={{ position: 'relative', display: 'inline-block', width: '100%', height: '100%' }}>
```
