### ISSUE TITLE
Custom Drag Layer on FireFox 57 Causes artifacts on drop

### ISSUE THREAD

**Issue by benjaminZale** [react-dnd/react-dnd#929]
Steps to reproduce: Drag an item from the [Custom Drag Layer](http://react-dnd.github.io/react-dnd/examples-drag-around-custom-drag-layer.html) demo.  When you let go of the mouse there are artifacts on the screen from the dragging style.

**Comment by cormacrelf** [comment]
I found a workaround. This appears to be a FF rendering bug, where it isn't re-painting even though a full-screeen `position:fixed` div just got removed. It appears, however, that if you animate an unimportant property, like a 0-width border's color, you can force it to repaint and in general the last repaint sneaks under the radar. As far as I can tell from paint flashing, browsers actually elide the whole repaint (because there is no border anyway) but it appears to make FF do one more repaint, so I'm happy.

Style the div that receives `translate3d(x, y, 0)` like so:

```css
@keyframes animatedBorder {
    from { border-color: rgba(0,0,0,0); }
    to { border-color: rgba(0,0,0,1); }
}
.firefox-bug {
    position: absolute;
    animation-name: animatedBorder;
    animation-duration: 1.0s;
    animation-iteration-count: infinite;
    animation-timing-function: linear;
}
```
